### ISSUE TITLE
Highlight the name of a defined function/operator

### ISSUE THREAD

**Issue by jayfoad** [Alhadis/language-apl#10]
When looking at the header line of a defined function or operator, it's really useful to the have the name of the function/operator highlighted. Currently it's the same colour as the result, arguments, operands and locals ([example](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-apl%2Fac5db0be8508e765541b03c7e3ace7db0a818959%2Fgrammars%2Fapl.cson&grammar_text=&code_source=from-text&code_url=&code=%E2%88%87+r%E2%86%90x+%28f+op+g%29+y%3Ba%3Bb%3Bc%0D%0A%E2%88%87)).

Currently we use scopes like **entity.function.arguments.left.optional.apl** and **entity.function.local-variables.apl**, which all end up coloured like **entity**.

Perhaps it would be better to use **entity.function.name.apl** only for the name of the function/operator, and for all other names on the header line use **variable.other.apl** just like we do when those names are mentioned in the body of the function.

**Comment by Alhadis** [comment]
Lightshow is currently down for maintenance, but definition headers should now look something like this:

<img src="https://user-images.githubusercontent.com/2346707/41717796-40a7354e-759e-11e8-8862-d8d6b3bce172.png" alt="Figure 1" width="280" />

This is a hack: I'm (ab)using the **markup.bold** scope to ensure unambiguous highlighting.

**Comment by jayfoad** [comment]
> Lightshow is currently down for maintenance

... still. Any idea if/when it might come back up?

**Comment by Alhadis** [comment]
I'm afraid not. There's an issue filled upstream where you can subscribe for updates: github/linguist#4168

Until then, a workaround might be to install Atom, `language-apl` and a syntax theme deliberately designed to look close to the colours used by GitHub: https://atom.io/themes/github-atom-light-syntax

It should be enough to tide you over. =)

**Comment by jayfoad** [comment]
This seems to be working for niladic and dyadic functions, but not monadic functions. For [example](https://github.com/Dyalog/MiServer/blob/master/Core/MiServer.dyalog):

```apl
    ∇ onIdle
      :Access Public Overridable
    ⍝ Idle time handler - called when the server has gone idle for a period of time
    ∇

    ∇ Error req
      :Access Public Overridable
    ⍝ Handle trapped errors
      req.Response.HTML←'<font face="APL385 Unicode" color="red">',(⊃,/⎕DM,¨⊂'<br/>'),'</font>'
      req.Fail 500 ⍝ Internal Server Error
      1 Log ⎕DM
    ∇

    ∇ level Log msg
      :Access Public overridable
    ⍝ Logs server messages
    ⍝ levels implemented in MildServer are:
    ⍝ 1-error/important, 2-warning, 4-informational, 8-transaction (GET/POST)
      :If Config.LogMessageLevel bit level ⍝ if set to display this level of message
          ⎕←msg ⍝ display it
      :EndIf
    ∇
```
... `onIdle` and `Log` are correctly bolded, but `Error` is not.

**Comment by Alhadis** [comment]
**Tip:** You can get syntax highlighted code-blocks by typing the name of the language after the first three backticks:

~~~~~~markdown
```apl
∇ onIdle
     :Access Public Overridable
∇
```
~~~~~~

But yeah, I see what you mean. 🤔 I'll look into it...

**Comment by Alhadis** [comment]
One of my least favourite things about the TextMate system is when you screw up, it accepts it silently without even *hinting* at what you may have done wrong. It offers you no guidance, or clues, just a stopwatch to see how long an obvious mistake like this would take me to pick up on....

~~~diff
@@ apl @@@
 12: {name: "keyword.operator.assignment.apl"}
-13: {name: "entity.function.name.apl", captures: {0: patterns: [include: "#embolden"]}}
+13: {name: "entity.function.name.apl", patterns: [include: "#embolden"]}
~~~

It's fortunate that you caught me at the right time, BTW. I'm scabbing somebody else's MacBook from them so I can get shitloads of Atom-related stuff that's gathered up since my regular one died. :(

**Comment by jayfoad** [comment]
Could you take a look at the highlighting of these 95 syntactically valid ways of defining a function or operator called `f` in Dyalog APL?

```apl
∇f
∇
∇f y
∇
∇f (y z)
∇
∇(p f) y
∇
∇(p f) (y z)
∇
∇(p f q) y
∇
∇(p f q) (y z)
∇
∇x f y
∇
∇x f (y z)
∇
∇x (p f) y
∇
∇x (p f) (y z)
∇
∇x (p f q) y
∇
∇x (p f q) (y z)
∇
∇{x} f y
∇
∇{x} f (y z)
∇
∇{x} (p f) y
∇
∇{x} (p f) (y z)
∇
∇{x} (p f q) y
∇
∇{x} (p f q) (y z)
∇
∇r←f
∇
∇r←f y
∇
∇r←f (y z)
∇
∇r←(p f) y
∇
∇r←(p f) (y z)
∇
∇r←(p f q) y
∇
∇r←(p f q) (y z)
∇
∇r←x f y
∇
∇r←x f (y z)
∇
∇r←x (p f) y
∇
∇r←x (p f) (y z)
∇
∇r←x (p f q) y
∇
∇r←x (p f q) (y z)
∇
∇r←{x} f y
∇
∇r←{x} f (y z)
∇
∇r←{x} (p f) y
∇
∇r←{x} (p f) (y z)
∇
∇r←{x} (p f q) y
∇
∇r←{x} (p f q) (y z)
∇
∇(r s)←f
∇
∇(r s)←f y
∇
∇(r s)←f (y z)
∇
∇(r s)←(p f) y
∇
∇(r s)←(p f) (y z)
∇
∇(r s)←(p f q) y
∇
∇(r s)←(p f q) (y z)
∇
∇(r s)←x f y
∇
∇(r s)←x f (y z)
∇
∇(r s)←x (p f) y
∇
∇(r s)←x (p f) (y z)
∇
∇(r s)←x (p f q) y
∇
∇(r s)←x (p f q) (y z)
∇
∇(r s)←{x} f y
∇
∇(r s)←{x} f (y z)
∇
∇(r s)←{x} (p f) y
∇
∇(r s)←{x} (p f) (y z)
∇
∇(r s)←{x} (p f q) y
∇
∇(r s)←{x} (p f q) (y z)
∇
∇{r}←f
∇
∇{r}←f y
∇
∇{r}←f (y z)
∇
∇{r}←(p f) y
∇
∇{r}←(p f) (y z)
∇
∇{r}←(p f q) y
∇
∇{r}←(p f q) (y z)
∇
∇{r}←x f y
∇
∇{r}←x f (y z)
∇
∇{r}←x (p f) y
∇
∇{r}←x (p f) (y z)
∇
∇{r}←x (p f q) y
∇
∇{r}←x (p f q) (y z)
∇
∇{r}←{x} f y
∇
∇{r}←{x} f (y z)
∇
∇{r}←{x} (p f) y
∇
∇{r}←{x} (p f) (y z)
∇
∇{r}←{x} (p f q) y
∇
∇{r}←{x} (p f q) (y z)
∇
∇{(r s)}←f
∇
∇{(r s)}←f y
∇
∇{(r s)}←f (y z)
∇
∇{(r s)}←(p f) y
∇
∇{(r s)}←(p f) (y z)
∇
∇{(r s)}←(p f q) y
∇
∇{(r s)}←(p f q) (y z)
∇
∇{(r s)}←x f y
∇
∇{(r s)}←x f (y z)
∇
∇{(r s)}←x (p f) y
∇
∇{(r s)}←x (p f) (y z)
∇
∇{(r s)}←x (p f q) y
∇
∇{(r s)}←x (p f q) (y z)
∇
∇{(r s)}←{x} f y
∇
∇{(r s)}←{x} f (y z)
∇
∇{(r s)}←{x} (p f) y
∇
∇{(r s)}←{x} (p f) (y z)
∇
∇{(r s)}←{x} (p f q) y
∇
∇{(r s)}←{x} (p f q) (y z)
∇
```

When I try this in Lightshow, forms like `(p f) y` and `(p f q) y` look odd. They have both `p` and `f` in the same style, and both `q` and `)` in red.

**Comment by Alhadis** [comment]
@jayfoad It might be easier if you download [Atom](http://atom.io/) and install this package for yourself. Atom and GitHub/Lightshow all use the same highlighting engine, and there's [even an Atom package](https://atom.io/themes/github-atom-light-syntax) that replicates the same colours used on GitHub (which is what I used while Lightshow was offline).

I know IME is a barrier, which is why I added support for [typing APL using ASCII-fied mnemonics](https://github.com/Alhadis/language-apl/blob/366c4256fa2a74e385f2c26e5f57bff2ac8d3b62/snippets/apl.cson#L30-L168). For example, typing `O|` and hitting <kbd>TAB</kbd> inserts `⌽` into the editor. Better yet, if you have a system-wide IME installed for APL entry, you be able to use that instead.

**Comment by Alhadis** [comment]
Now then... having inspected those expressions you've given me, I can conclude this could be a Lightshow bug, or some flaky handling of newlines on their end. 😥 Because what I'm seeing in Atom (which has until recently been exactly the same as what I've seen on GitHub) differs to what we're now seeing, well, on GitHub:

**GitHub:**
~~~apl
∇(r s)←f
∇
∇(r s)←f y
∇
~~~


**Lightshow:**  
![screen shot 2018-08-10 at 8 28 23 pm](https://user-images.githubusercontent.com/2346707/43953386-2474bf80-9cdc-11e8-9cfb-c59257ebbbdf.png)


**Atom:** . 
<img src="https://user-images.githubusercontent.com/2346707/43953217-a00a0a8e-9cdb-11e8-84c8-6854692227f2.png" alt="Figure 2" />

**Comment by jayfoad** [comment]
> download Atom and install this package for yourself

Is there an easy way to try out your latest commits before they've been released?

> I know IME is a barrier

Not for me. X keyboard layouts for APL have been included in the Linux distros for many years now.

**Comment by Alhadis** [comment]
> Is there an easy way to try out your latest commits before they've been released?

Yes. Under your `~/.atom/packages`, you can replace the `language-apl` directory with a local checkout:

~~~console
$ cd ~/.atom/packages;
$ rm -rf language-apl;
$ git clone git@github.com:Alhadis/language-apl.git
~~~

That's really it. Atom loads every immediate folder under `~/.atom/packages` at startup, pretty much.

**Comment by jayfoad** [comment]
> When I try this in Lightshow, forms like (p f) y and (p f q) y look odd.

I guess someone has fixed something. It all looks good in Lightshow now. Thanks!

**Comment by Alhadis** [comment]
You can thank @kivikakk for her [hard work today](https://github.com/github/linguist/issues/4168#issuecomment-412771473) getting it back online. 😉

And good to know! Let me know if you spot any more issues.
